#!/usr/bin/env bash
# Convert EDTA *.TEanno.gff3 to simplified TE BED files.
# Run in the directory that contains the EDTA GFF3 outputs.
# Output: <Species>_<Accession>_EDTA.bed (chrom start end TE_class)
set -euo pipefail
sed "/#/d" ECD04_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Brapa_ECD04_EDTA.bed
sed "/#/d" C4012_v1_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bcarinata_C4012_v1_EDTA.bed
sed "/#/d" zd_1_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bcarinata_zd_1_EDTA.bed
sed "/#/d" ASM1677196v1_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bcarinata_ASM1677196v1_EDTA.bed
sed "/#/d" ASM4058406v1_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bcarinata_ASM4058406v1_EDTA.bed
sed "/#/d" 10167_v1_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bcarinata_10167_v1_EDTA.bed
sed "/#/d" HJ_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bjuncea_HJ_EDTA.bed
sed "/#/d" varuna.v0_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bjuncea_varuna.v0_EDTA.bed
sed "/#/d" tumida.v1.5_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bjuncea_tumida.v1.5_EDTA.bed
sed "/#/d" W1701_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Boleracea_W1701_EDTA.bed
sed "/#/d" PL021_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Boleracea_PL021_EDTA.bed
sed "/#/d" D101_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Boleracea_D101_EDTA.bed
sed "/#/d" HDEM_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Boleracea_HDEM_EDTA.bed
sed "/#/d" No.06-9-28_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Boleracea_No.06-9-28_EDTA.bed
sed "/#/d" M249_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Boleracea_M249_EDTA.bed
sed "/#/d" C2_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnigra_C2_EDTA.bed
sed "/#/d" Ni100_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnigra_Ni100_EDTA.bed
sed "/#/d" Sangam_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnigra_Sangam_EDTA.bed
sed "/#/d" CN115125_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnigra_CN115125_EDTA.bed
sed "/#/d" Gangan_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_Gangan_EDTA.bed
sed "/#/d" Express617_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_Express617_EDTA.bed
sed "/#/d" Westar_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_Westar_EDTA.bed
sed "/#/d" Ningyou7_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_Ningyou7_EDTA.bed
sed "/#/d" No2127_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_No2127_EDTA.bed
sed "/#/d" Zheyou7_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_Zheyou7_EDTA.bed
sed "/#/d" Z1_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Brapa_Z1_EDTA.bed
sed "/#/d" Chiifu_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Brapa_Chiifu_EDTA.bed
sed "/#/d" HSCT_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Brapa_HSCT_EDTA.bed
sed "/#/d" AJ_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Brapa_AJ_EDTA.bed
sed "/#/d" ZS11_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_ZS11_EDTA.bed
sed "/#/d" JS_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Boleracea_JS_EDTA.bed
sed "/#/d" Darmor_v10_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_Darmor_v10_EDTA.bed
sed "/#/d" Xiaoyun_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_Xiaoyun_EDTA.bed
sed "/#/d" Tapidor_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_Tapidor_EDTA.bed
sed "/#/d" QuintaA_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_QuintaA_EDTA.bed
sed "/#/d" Shengli_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Bnapus_Shengli_EDTA.bed
sed "/#/d" 07-DH-33_chromosomes.fa.mod.EDTA.TEanno.gff3 |sed "/Parent/d"|sed -e "s/;/\t/g"| awk '{print $1"\t"$4"\t"$5"\t"$3"\t"$11}'|sed "s/Classification=//g"|awk 'BEGIN {OFS="\t"} {if ($4 == "repeat_region") $4 = $5; print}'|cut -f1,2,3,5|sed "s/Copia_LTR_retrotransposon/LTR\/Copia/g"| sed "s/Gypsy_LTR_retrotransposon/LTR\/Gypsy/g"|sed "s/LTR_retrotransposon/LTR\/unknown/g" > Boleracea_07-DH-33_EDTA.bed
