EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Boleracea/PL021/PL021_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Boleracea/D101/D101_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Boleracea/HDEM/HDEM_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Boleracea/No.06-9-28/No.06-9-28_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Boleracea/M249/M249_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Boleracea/JS/JS_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Boleracea/07-DH-33/07-DH-33_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnigra/C2/C2_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnigra/Ni100/Ni100_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnigra/Sangam/Sangam_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnigra/CN115125/CN115125_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/ZS11/ZS11_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/Shengli/Shengli_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/Xiaoyun/Xiaoyun_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/Darmor_v10/Darmor_v10_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/Tapidor/Tapidor_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/QuintaA/QuintaA_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/Gangan/Gangan_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/Express617/Express617_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/Westar/Westar_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/Ningyou7/Ningyou7_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/No2127/No2127_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bnapus/Zheyou7/Zheyou7_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Brapa/Z1/Z1_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Brapa/Chiifu/Chiifu_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Brapa/HSCT/HSCT_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Brapa/AJ/AJ_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Brapa/ECD04/ECD04_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bcarinata/ASM4058406v1/ASM4058406v1_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bcarinata/10167_v1/10167_v1_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bjuncea/HJ/HJ_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bjuncea/varuna.v0/varuna.v0_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Bjuncea/tumida.v1.5/tumida.v1.5_chromosomes.fa --anno 1 --threads 64
EDTA.pl --genome Brassica_Genomes/edta_chromosomes/Boleracea/W1701/W1701_chromosomes.fa --anno 1 --threads 64